version: '3'
services:
    postgres:
        image: postgres:11.3-alpine
        env_file: .env
        ports:
          - 5432:5432
        restart: unless-stopped
        volumes:
          - /data/sentocks/postgres:/var/lib/postgres/data

    nginx:
        build: ./webpage
        restart: unless-stopped
        ports:
          - 7839:80
        depends_on:
          - postgres
          - api

    twippy:
        build: ./twippy
        restart: "always"
        depends_on:
          - postgres
        entrypoint: ["python", "twippy.py"]

    api:
        build: ./twippy
        restart: "on-failure"
        depends_on:
          - postgres
        entrypoint: ["python", "api.py"]
