version: '3'
services:
    postgres:
        image: postgres:11.3-alpine
        env_file: .env
        ports:
          - 5432:5432 #127.0.0.1:
        restart: unless-stopped
        volumes:
          - ./data/sentocks/postgres:/var/lib/postgres/data

    caddy:
        build: ./webpage
        env_file: .env
        restart: unless-stopped
        ports:
          - 80:80
          - 443:443
          - 2015:2015
        depends_on:
          - postgres
          - server
        volumes:
          - "./data/sentocks/caddy/data:/root/.caddy"
          - "./data/sentocks/caddy/logs:/var/log"
            #- "./webpage/front:/srv"
          - "docs:/srv/docs"
    twippy:
        build: ./twippy
        env_file: .env
        restart: "always"
        depends_on:
          - server
        volumes:
          - docs:/docs

    tokentest:
        build: ./twippy
        env_file: .env
        entrypoint: python tokentest.py
    
    server:
        build: ./server
        restart: "always"
        env_file: .env
        ports:
          - 127.0.0.1:10000:10000
        depends_on:
          - postgres
        command: ./server

    server_docs:
        build: ./server
        ports:
          - 6060:6060
        depends_on:
          - server
        command: godoc -http=:6060

    josh:
        build: ./josh
        env_file: .env
        restart: "always"
        depends_on:
          - server
        command: ./josh

    josh_docs:
        build: ./josh
        depends_on:
          - josh
        ports:
          - 6061:6061
        command: godoc -http=:6061

volumes:
  docs:
