version: '3'
services:
    postgres:
        image: postgres:11.3-alpine
        env_file: .env
        ports:
          - 127.0.0.1:5432:5432
        restart: unless-stopped
        volumes:
          - ./data:/var/lib/postgres/data
            #- /data/sentocks/postgres:/var/lib/postgres/data

    caddy:
        build: ./webpage
        env_file: .env
        restart: unless-stopped
        ports:
          - 80:80
          - 443:443
          - 2015:2015
        depends_on:
          - postgres
          - server
          - server_docs
          - josh_docs
        volumes:
          - "./data/sentocks/caddy/data:/root/.caddy"
          - "./data/sentocks/caddy/logs:/var/log"
          - twippy_docs:/srv/docs/twippy

    twippy:
        build: ./twippy
        env_file: .env
        restart: "always"
        volumes:
          - twippy_docs:/docs
    
    server:
        build: ./server
        command: ./server
        restart: "always"
        env_file: .env
        ports:
          - 127.0.0.1:10000:10000
        depends_on:
          - postgres

    server_docs:
        build: ./server
        command: godoc -http=:6061
        restart: "always"
        env_file: .env
        ports: 
          - 6061:6061
        depends_on:
          - server

    josh:
        build: ./josh
        env_file: .env
        restart: "always"
        depends_on:
          - server
        command: ./josh

    josh_docs:
        build: ./josh
        command: godoc -http=:6060
        ports:
          - 6060:6060
        depends_on:
          - josh

volumes:
  twippy_docs:
