version: '3'
services: 
    db:
        image: postgres:11.3-alpine
        #env_file: .env
        restart: unless-stopped
        ports: 
            - 5432:5432
    nginx:
        build: ./webpage
        restart: unless-stopped
        ports: 
            - 80:80
    flask_api:
        build: ./flask_api
        restart: unless-stopped
        ports:
            - 3000:3000
    twitter_polling:
        build: ./twitter
        restart: "no"