version: '3'
services:
    postgres:
        image: postgres:11.3-alpine
        env_file: .env
        ports:
          - 5432:5432
        restart: unless-stopped
        volumes:
          #  - /data/sentocks/postgres:/var/lib/postgres/data
          - ./data:/var/lib/postgres/data
    nginx:
        build: ./webpage
        restart: unless-stopped
        ports:
          - 5050:80
        depends_on:
          - postgres
          - server

    twippy:
        build: ./twippy
        restart: "always"
    
    server:
        build: ./server
        restart: "always"
        ports:
          - 10000:10000
        depends_on:
          - postgres

    josh:
        build: ./josh
        restart: "always"
        depends_on:
          - server
