version: '3'
services:
    postgres:
        image: postgres:11.3-alpine
        env_file: .env
        restart: unless-stopped
    nginx:
        build: ./webpage
        restart: unless-stopped
        ports:
          - 7839:80
        depends_on:
          - postgres
          - flask_api
    flask_api:
        build: ./flask_api
        restart: unless-stopped
        depends_on:
          - postgres
    twitter_polling:
        build: ./twitter
        restart: "no"
        depends_on:
          - postgres
