version: '3'
services:
    postgres:
        image: postgres:11.3-alpine
        env_file: .env
        ports:
          - 127.0.0.1:5432:5432
        restart: unless-stopped
        volumes:
          - ./data:/var/lib/postgres/data
            #- /data/sentocks/postgres:/var/lib/postgres/data

    caddy:
        build: ./webpage
        env_file: .env
        restart: unless-stopped
        ports:
          - 80:80
          - 443:443
          - 2015:2015
        depends_on:
          - postgres
          - server
        volumes:
          - "./data/sentocks/caddy/data:/root/.caddy"
          - "./data/sentocks/caddy/logs:/var/log"
          - docs:/srv/docs

    twippy:
        build: ./twippy
        env_file: .env
        restart: "always"
        volumes:
          - docs:/docs
    
    server:
        build: ./server
        restart: "always"
        env_file: .env
        ports:
          - 127.0.0.1:10000:10000
        depends_on:
          - postgres

    josh:
        build: ./josh
        env_file: .env
        restart: "always"
        depends_on:
          - server

volumes:
  docs:
