name: Go
on: push
jobs:

  test:
    name: Testing
    runs-on: ubuntu-latest
    env:
      CALENDAR_TEST: Yes
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Grabbing dependencies
      run: |
        go get -v -t -u ./...
        go get -v -t -u github.com/stretchr/testify      
    - name: Test
      run: |
        docker-compose up -d postgres
        sleep 3
        go test -v -count=1 ./...
